akka {
  actor {
    provider = "cluster"
    serialization-bindings {
      "com.example.SpawnProtocol$Serializable" = jackson-cbor
    }
  }
  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.port = 0
  }
  cluster {
    seed-nodes = ["akka://SpawnSystem@127.0.0.1:2551"]
  }
}